# Top-level configuration for Caryatid process - REST Hello, World! version

[module.rest-server]
address = "127.0.0.1"
port = 4340

[module.rest-server-2]
class = "rest-server"
topic = "rest2"
port = 4341

[module.rest-hello-world]
topic = "rest.get.hello"

[module.rest-hello-world-2]
class = "rest-hello-world"
topic = "rest2.get.hello2"

[message-bus.internal]
class = "in-memory"
workers = 10

# Message routing
[[message-router.route]]  # Everything goes to internal
pattern = "#"
bus = [ "internal" ]

