# Caryatid framework workspace root

[workspace]
members = [
    "sdk",             # The SDK library for modules
    "sample",          # Sample 'main' provider
    "modules/sample_subscriber",  # An example subscriber module
    "modules/sample_publisher",   # An example subscriber module
]

resolver = "2"
