# Caryatid framework workspace root

[workspace]
members = [
    "sdk",                # The SDK library for modules
    "process",            # Library for processes
    "examples/simple",    # Sample process
]

resolver = "2"
