# Caryatid framework workspace root

[workspace]
members = [
    "process",         # Executable for a single process
    "sdk",             # The SDK library for modules
    "modules/sample-subscriber",  # An example subscriber module
    "modules/sample-publisher",   # An example subscriber module
]

resolver = "2"
