# Top-level configuration for example pub-sub Caryatid process

[module.subscriber]
topic = "#"

[message-bus.external]
class = "rabbit-mq"
url = "amqp://127.0.0.1:5672/%2f"
exchange = "caryatid"

# Message routing
[[message-router.route]]  # Only external
pattern = "#"
bus = "external"

