# Top-level configuration for Caryatid process

[typed-subscriber]
enabled = true
topic = "sample.#"

[typed-publisher]
enabled = true
topic = "sample.test"

[message-bus.external]
class = "rabbit-mq"
url = "amqp://127.0.0.1:5672/%2f"
exchange = "caryatid"

[message-bus.internal]
class = "in-memory"
workers = 10

# Message routing
[[message-router.route]]  # Everything goes to both
pattern = "#"
bus = [ "internal", "external" ]

