# Top-level configuration for Caryatid process

[sample-subscriber]
enabled = true
topic = "sample.test"

[sample-publisher]
enabled = true
topic = "sample.test"

#[message-bus.rabbit-mq]

[message-bus.in-memory]
workers = 10


