# Configuration for Caryatid performance-testing process

[perf-publisher]
enabled = true
topic = "performance.test"

# Number of messages per thread
count = 100000

# Number of threads
threads = 4

# Length of 'data' string
length = 1000000

[perf-subscriber]
enabled = true
topic = "performance.test"

#[message-bus.rabbit-mq]

[message-bus.in-memory]
workers = 1


