# Configuration for Caryatid performance-testing process

[module.publisher]
topic = "performance.test"

# Number of messages per thread
count = 1000000

# Number of threads
threads = 1

# Length of 'data' string
length = 1000000

[module.subscriber]
topic = "performance.test"

[message-bus.external]
class = "rabbit-mq"
url = "amqp://127.0.0.1:5672/%2f"
exchange = "caryatid"

[message-bus.internal]
class = "in-memory"
workers = 10

[[message-router.route]]
pattern = "#"
bus = "internal"

