# Configuration for Caryatid performance-testing process

[perf-publisher]
enabled = true
topic = "performance.test"
count = 1000000
threads = 1

[perf-subscriber]
enabled = true
topic = "performance.test"

#[message-bus.rabbit-mq]

[message-bus.in-memory]
workers = 1


