# Top-level configuration for Caryatid process

[simple-subscriber]
enabled = true
topic = "sample.test"

[simple-publisher]
enabled = true
topic = "sample.test"

#[message-bus.rabbit-mq]

[message-bus.in-memory]
workers = 10


