# Top-level configuration for example pub-sub Caryatid process

[module.subscriber]
topic = "sample.#"

[module.publisher]
topic = "sample.test"

[message-bus.external]
class = "rabbit-mq"
url = "amqp://127.0.0.1:5672/%2f"
exchange = "caryatid"

[message-bus.internal]
class = "in-memory"
workers = 10

# Message routing
[[message-router.route]]  # Everything else goes to both
pattern = "#"
bus = [ "internal", "external" ]

