# Caraytid process - loads and runs modules
[package]
name = "caryatid_process"
version = "0.1.0"
edition = "2021"
authors = ["Paul Clark <paul.clark@iohk.io>"]
description = "Caryatid process"

[dependencies]
caryatid_sdk = { path = "../sdk" }
futures = "0.3"
anyhow = "1.0"
tokio = { version = "1", features = ["full"] }
config = "0.14.0"
tracing = "0.1.40"
lapin = "2.5.0"
serde = "1.0.210"
serde_json = "1.0"
serde_cbor = "0.11.2"

[lib]
path = "src/process.rs"
