# Top-level configuration for Caryatid process

[paths]
modules = "./target/debug"

[modules.sample]
lib = "libsample_module.so"
foo = "bar"

#[message-bus.rabbit-mq]

[message-bus.in-memory]
workers = 10

