# Top-level configuration for Caryatid process

[paths]
modules = "./target/debug"

[modules.sample-subscriber]
lib = "libsample_subscriber.so"
topic = "sample.test"

[modules.sample-publisher]
lib = "libsample_publisher.so"
topic = "sample.test"

#[message-bus.rabbit-mq]

[message-bus.in-memory]
workers = 10

