# Macros for defining Caryatid modules

[package]
name = "caryatid-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"
anyhow = "1.0"
